// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: order.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Side int32

const (
	Side_SIDE_UNKNOWN Side = 0
	Side_SIDE_BUY     Side = 1
	Side_SIDE_SELL    Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNKNOWN",
		1: "SIDE_BUY",
		2: "SIDE_SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNKNOWN": 0,
		"SIDE_BUY":     1,
		"SIDE_SELL":    2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

type OrderType int32

const (
	OrderType_ORDER_TYPE_UNKNOWN       OrderType = 0
	OrderType_ORDER_TYPE_LIMIT         OrderType = 1
	OrderType_ORDER_TYPE_MARKET        OrderType = 2
	OrderType_ORDER_TYPE_POST_ONLY     OrderType = 3
	OrderType_ORDER_TYPE_FOK           OrderType = 4
	OrderType_ORDER_TYPE_IOC           OrderType = 5
	OrderType_ORDER_TYPE_AON           OrderType = 6
	OrderType_ORDER_TYPE_ICEBERG       OrderType = 7
	OrderType_ORDER_TYPE_CANCEL        OrderType = 8
	OrderType_ORDER_TYPE_SYSTEM_CANCEL OrderType = 9
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNKNOWN",
		1: "ORDER_TYPE_LIMIT",
		2: "ORDER_TYPE_MARKET",
		3: "ORDER_TYPE_POST_ONLY",
		4: "ORDER_TYPE_FOK",
		5: "ORDER_TYPE_IOC",
		6: "ORDER_TYPE_AON",
		7: "ORDER_TYPE_ICEBERG",
		8: "ORDER_TYPE_CANCEL",
		9: "ORDER_TYPE_SYSTEM_CANCEL",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNKNOWN":       0,
		"ORDER_TYPE_LIMIT":         1,
		"ORDER_TYPE_MARKET":        2,
		"ORDER_TYPE_POST_ONLY":     3,
		"ORDER_TYPE_FOK":           4,
		"ORDER_TYPE_IOC":           5,
		"ORDER_TYPE_AON":           6,
		"ORDER_TYPE_ICEBERG":       7,
		"ORDER_TYPE_CANCEL":        8,
		"ORDER_TYPE_SYSTEM_CANCEL": 9,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

type SelfTradeWMType int32

const (
	SelfTradeWMType_STP_AST SelfTradeWMType = 0
	SelfTradeWMType_STP_DC  SelfTradeWMType = 1
	SelfTradeWMType_STP_CO  SelfTradeWMType = 2
	SelfTradeWMType_STP_CN  SelfTradeWMType = 3
	SelfTradeWMType_STP_CB  SelfTradeWMType = 4
)

// Enum value maps for SelfTradeWMType.
var (
	SelfTradeWMType_name = map[int32]string{
		0: "STP_AST",
		1: "STP_DC",
		2: "STP_CO",
		3: "STP_CN",
		4: "STP_CB",
	}
	SelfTradeWMType_value = map[string]int32{
		"STP_AST": 0,
		"STP_DC":  1,
		"STP_CO":  2,
		"STP_CN":  3,
		"STP_CB":  4,
	}
)

func (x SelfTradeWMType) Enum() *SelfTradeWMType {
	p := new(SelfTradeWMType)
	*p = x
	return p
}

func (x SelfTradeWMType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SelfTradeWMType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[2].Descriptor()
}

func (SelfTradeWMType) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[2]
}

func (x SelfTradeWMType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SelfTradeWMType.Descriptor instead.
func (SelfTradeWMType) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

type OrderState int32

const (
	OrderState_ORDER_STATE_UNKNOWN          OrderState = 0
	OrderState_ORDER_STATE_PENDING          OrderState = 1
	OrderState_ORDER_STATE_ACCEPTED         OrderState = 2
	OrderState_ORDER_STATE_FILLED           OrderState = 3
	OrderState_ORDER_STATE_PARTIAL_FILLED   OrderState = 4
	OrderState_ORDER_STATE_CANCELED         OrderState = 5
	OrderState_ORDER_STATE_PARTIAL_CANCELED OrderState = 6
	OrderState_ORDER_STATE_FAILED           OrderState = 7
	OrderState_ORDER_STATE_ERROR            OrderState = 8
)

// Enum value maps for OrderState.
var (
	OrderState_name = map[int32]string{
		0: "ORDER_STATE_UNKNOWN",
		1: "ORDER_STATE_PENDING",
		2: "ORDER_STATE_ACCEPTED",
		3: "ORDER_STATE_FILLED",
		4: "ORDER_STATE_PARTIAL_FILLED",
		5: "ORDER_STATE_CANCELED",
		6: "ORDER_STATE_PARTIAL_CANCELED",
		7: "ORDER_STATE_FAILED",
		8: "ORDER_STATE_ERROR",
	}
	OrderState_value = map[string]int32{
		"ORDER_STATE_UNKNOWN":          0,
		"ORDER_STATE_PENDING":          1,
		"ORDER_STATE_ACCEPTED":         2,
		"ORDER_STATE_FILLED":           3,
		"ORDER_STATE_PARTIAL_FILLED":   4,
		"ORDER_STATE_CANCELED":         5,
		"ORDER_STATE_PARTIAL_CANCELED": 6,
		"ORDER_STATE_FAILED":           7,
		"ORDER_STATE_ERROR":            8,
	}
)

func (x OrderState) Enum() *OrderState {
	p := new(OrderState)
	*p = x
	return p
}

func (x OrderState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderState) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[3].Descriptor()
}

func (OrderState) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[3]
}

func (x OrderState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderState.Descriptor instead.
func (OrderState) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

type Order struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	SeqId   int64                  `protobuf:"varint,1,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	UserId  int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId int64                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Side    Side                   `protobuf:"varint,4,opt,name=side,proto3,enum=dto.Side" json:"side,omitempty"`
	Type    OrderType              `protobuf:"varint,5,opt,name=type,proto3,enum=dto.OrderType" json:"type,omitempty"`
	State   OrderState             `protobuf:"varint,6,opt,name=state,proto3,enum=dto.OrderState" json:"state,omitempty"`
	// Decimal 类型在 Proto 中通常使用 string 传输以保证精度
	// 接收端使用 decimal.NewFromString(price) 解析
	Price          string          `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	UnfilledAmount string          `protobuf:"bytes,8,opt,name=unfilled_amount,json=unfilledAmount,proto3" json:"unfilled_amount,omitempty"`
	CircuitRate    string          `protobuf:"bytes,9,opt,name=circuit_rate,json=circuitRate,proto3" json:"circuit_rate,omitempty"`
	CreateAt       int64           `protobuf:"varint,10,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	Stp            SelfTradeWMType `protobuf:"varint,11,opt,name=stp,proto3,enum=dto.SelfTradeWMType" json:"stp,omitempty"`
	PullTime       int64           `protobuf:"varint,12,opt,name=pull_time,json=pullTime,proto3" json:"pull_time,omitempty"`
	// 批量撤单的订单ID集合
	Extra         string      `protobuf:"bytes,13,opt,name=extra,proto3" json:"extra,omitempty"`
	Taker         string      `protobuf:"bytes,14,opt,name=taker,proto3" json:"taker,omitempty"`
	Maker         string      `protobuf:"bytes,15,opt,name=maker,proto3" json:"maker,omitempty"`
	Pre           *Order      `protobuf:"bytes,16,opt,name=pre,proto3" json:"pre,omitempty"`
	Next          *Order      `protobuf:"bytes,17,opt,name=next,proto3" json:"next,omitempty"`
	Parent        *PriceLevel `protobuf:"bytes,18,opt,name=Parent,proto3" json:"Parent,omitempty"` // 反向指针：指向它所属的“价格层级”对象
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *Order) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Order) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNKNOWN
}

func (x *Order) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNKNOWN
}

func (x *Order) GetState() OrderState {
	if x != nil {
		return x.State
	}
	return OrderState_ORDER_STATE_UNKNOWN
}

func (x *Order) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Order) GetUnfilledAmount() string {
	if x != nil {
		return x.UnfilledAmount
	}
	return ""
}

func (x *Order) GetCircuitRate() string {
	if x != nil {
		return x.CircuitRate
	}
	return ""
}

func (x *Order) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *Order) GetStp() SelfTradeWMType {
	if x != nil {
		return x.Stp
	}
	return SelfTradeWMType_STP_AST
}

func (x *Order) GetPullTime() int64 {
	if x != nil {
		return x.PullTime
	}
	return 0
}

func (x *Order) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *Order) GetTaker() string {
	if x != nil {
		return x.Taker
	}
	return ""
}

func (x *Order) GetMaker() string {
	if x != nil {
		return x.Maker
	}
	return ""
}

func (x *Order) GetPre() *Order {
	if x != nil {
		return x.Pre
	}
	return nil
}

func (x *Order) GetNext() *Order {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *Order) GetParent() *PriceLevel {
	if x != nil {
		return x.Parent
	}
	return nil
}

type OrderBookSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoinGroup     uint32                 `protobuf:"varint,1,opt,name=coin_group,json=coinGroup,proto3" json:"coin_group,omitempty"`    // 交易对，如 BTC-USDT
	SequenceId    uint64                 `protobuf:"varint,2,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"` // 撮合引擎的定序 ID (非常重要，用于对账)
	Asks          []*Order               `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`                                // 卖单树扁平化
	Bids          []*Order               `protobuf:"bytes,4,rep,name=bids,proto3" json:"bids,omitempty"`                                // 买单树扁平化
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookSnapshot) Reset() {
	*x = OrderBookSnapshot{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookSnapshot) ProtoMessage() {}

func (x *OrderBookSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookSnapshot.ProtoReflect.Descriptor instead.
func (*OrderBookSnapshot) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderBookSnapshot) GetCoinGroup() uint32 {
	if x != nil {
		return x.CoinGroup
	}
	return 0
}

func (x *OrderBookSnapshot) GetSequenceId() uint64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *OrderBookSnapshot) GetAsks() []*Order {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *OrderBookSnapshot) GetBids() []*Order {
	if x != nil {
		return x.Bids
	}
	return nil
}

// c
type OrderResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 订单ID
	OrderId int64 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// 用户ID
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 角色 (taker/maker)
	Role string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	// 价格 (使用 optional 实现 omitempty 效果)
	Price *string `protobuf:"bytes,4,opt,name=price,proto3,oneof" json:"price,omitempty"`
	// 未成交数量 (taker 专用)
	UnfilledAmount *string `protobuf:"bytes,5,opt,name=unfilled_amount,json=unfilledAmount,proto3,oneof" json:"unfilled_amount,omitempty"`
	// 已成交数量 (maker 专用)
	FilledAmount *string `protobuf:"bytes,6,opt,name=filled_amount,json=filledAmount,proto3,oneof" json:"filled_amount,omitempty"`
	// 订单状态
	State *string `protobuf:"bytes,7,opt,name=state,proto3,oneof" json:"state,omitempty"`
	// Taker 地址
	Taker string `protobuf:"bytes,8,opt,name=taker,proto3" json:"taker,omitempty"`
	// Maker 地址
	Maker         string `protobuf:"bytes,9,opt,name=maker,proto3" json:"maker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResult) Reset() {
	*x = OrderResult{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResult) ProtoMessage() {}

func (x *OrderResult) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResult.ProtoReflect.Descriptor instead.
func (*OrderResult) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderResult) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderResult) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderResult) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *OrderResult) GetPrice() string {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return ""
}

func (x *OrderResult) GetUnfilledAmount() string {
	if x != nil && x.UnfilledAmount != nil {
		return *x.UnfilledAmount
	}
	return ""
}

func (x *OrderResult) GetFilledAmount() string {
	if x != nil && x.FilledAmount != nil {
		return *x.FilledAmount
	}
	return ""
}

func (x *OrderResult) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *OrderResult) GetTaker() string {
	if x != nil {
		return x.Taker
	}
	return ""
}

func (x *OrderResult) GetMaker() string {
	if x != nil {
		return x.Maker
	}
	return ""
}

type PriceLevel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 价格
	Price float64 `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	// 该价格档总挂单量
	TotalVolume float64 `protobuf:"fixed64,2,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"`
	// 该价格档下的订单列表
	Head          *Order `protobuf:"bytes,3,opt,name=head,proto3" json:"head,omitempty"`
	Tail          *Order `protobuf:"bytes,4,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *PriceLevel) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceLevel) GetTotalVolume() float64 {
	if x != nil {
		return x.TotalVolume
	}
	return 0
}

func (x *PriceLevel) GetHead() *Order {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *PriceLevel) GetTail() *Order {
	if x != nil {
		return x.Tail
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x03dto\"\xa9\x04\n" +
	"\x05Order\x12\x15\n" +
	"\x06seq_id\x18\x01 \x01(\x03R\x05seqId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\x12\x1d\n" +
	"\x04side\x18\x04 \x01(\x0e2\t.dto.SideR\x04side\x12\"\n" +
	"\x04type\x18\x05 \x01(\x0e2\x0e.dto.OrderTypeR\x04type\x12%\n" +
	"\x05state\x18\x06 \x01(\x0e2\x0f.dto.OrderStateR\x05state\x12\x14\n" +
	"\x05price\x18\a \x01(\tR\x05price\x12'\n" +
	"\x0funfilled_amount\x18\b \x01(\tR\x0eunfilledAmount\x12!\n" +
	"\fcircuit_rate\x18\t \x01(\tR\vcircuitRate\x12\x1b\n" +
	"\tcreate_at\x18\n" +
	" \x01(\x03R\bcreateAt\x12&\n" +
	"\x03stp\x18\v \x01(\x0e2\x14.dto.SelfTradeWMTypeR\x03stp\x12\x1b\n" +
	"\tpull_time\x18\f \x01(\x03R\bpullTime\x12\x14\n" +
	"\x05extra\x18\r \x01(\tR\x05extra\x12\x14\n" +
	"\x05taker\x18\x0e \x01(\tR\x05taker\x12\x14\n" +
	"\x05maker\x18\x0f \x01(\tR\x05maker\x12\x1c\n" +
	"\x03pre\x18\x10 \x01(\v2\n" +
	".dto.OrderR\x03pre\x12\x1e\n" +
	"\x04next\x18\x11 \x01(\v2\n" +
	".dto.OrderR\x04next\x12'\n" +
	"\x06Parent\x18\x12 \x01(\v2\x0f.dto.PriceLevelR\x06Parent\"\x93\x01\n" +
	"\x11OrderBookSnapshot\x12\x1d\n" +
	"\n" +
	"coin_group\x18\x01 \x01(\rR\tcoinGroup\x12\x1f\n" +
	"\vsequence_id\x18\x02 \x01(\x04R\n" +
	"sequenceId\x12\x1e\n" +
	"\x04asks\x18\x03 \x03(\v2\n" +
	".dto.OrderR\x04asks\x12\x1e\n" +
	"\x04bids\x18\x04 \x03(\v2\n" +
	".dto.OrderR\x04bids\"\xc9\x02\n" +
	"\vOrderResult\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x19\n" +
	"\x05price\x18\x04 \x01(\tH\x00R\x05price\x88\x01\x01\x12,\n" +
	"\x0funfilled_amount\x18\x05 \x01(\tH\x01R\x0eunfilledAmount\x88\x01\x01\x12(\n" +
	"\rfilled_amount\x18\x06 \x01(\tH\x02R\ffilledAmount\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\a \x01(\tH\x03R\x05state\x88\x01\x01\x12\x14\n" +
	"\x05taker\x18\b \x01(\tR\x05taker\x12\x14\n" +
	"\x05maker\x18\t \x01(\tR\x05makerB\b\n" +
	"\x06_priceB\x12\n" +
	"\x10_unfilled_amountB\x10\n" +
	"\x0e_filled_amountB\b\n" +
	"\x06_state\"\x85\x01\n" +
	"\n" +
	"PriceLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12!\n" +
	"\ftotal_volume\x18\x02 \x01(\x01R\vtotalVolume\x12\x1e\n" +
	"\x04head\x18\x03 \x01(\v2\n" +
	".dto.OrderR\x04head\x12\x1e\n" +
	"\x04tail\x18\x04 \x01(\v2\n" +
	".dto.OrderR\x04tail*5\n" +
	"\x04Side\x12\x10\n" +
	"\fSIDE_UNKNOWN\x10\x00\x12\f\n" +
	"\bSIDE_BUY\x10\x01\x12\r\n" +
	"\tSIDE_SELL\x10\x02*\xf3\x01\n" +
	"\tOrderType\x12\x16\n" +
	"\x12ORDER_TYPE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x01\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x02\x12\x18\n" +
	"\x14ORDER_TYPE_POST_ONLY\x10\x03\x12\x12\n" +
	"\x0eORDER_TYPE_FOK\x10\x04\x12\x12\n" +
	"\x0eORDER_TYPE_IOC\x10\x05\x12\x12\n" +
	"\x0eORDER_TYPE_AON\x10\x06\x12\x16\n" +
	"\x12ORDER_TYPE_ICEBERG\x10\a\x12\x15\n" +
	"\x11ORDER_TYPE_CANCEL\x10\b\x12\x1c\n" +
	"\x18ORDER_TYPE_SYSTEM_CANCEL\x10\t*N\n" +
	"\x0fSelfTradeWMType\x12\v\n" +
	"\aSTP_AST\x10\x00\x12\n" +
	"\n" +
	"\x06STP_DC\x10\x01\x12\n" +
	"\n" +
	"\x06STP_CO\x10\x02\x12\n" +
	"\n" +
	"\x06STP_CN\x10\x03\x12\n" +
	"\n" +
	"\x06STP_CB\x10\x04*\xfb\x01\n" +
	"\n" +
	"OrderState\x12\x17\n" +
	"\x13ORDER_STATE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13ORDER_STATE_PENDING\x10\x01\x12\x18\n" +
	"\x14ORDER_STATE_ACCEPTED\x10\x02\x12\x16\n" +
	"\x12ORDER_STATE_FILLED\x10\x03\x12\x1e\n" +
	"\x1aORDER_STATE_PARTIAL_FILLED\x10\x04\x12\x18\n" +
	"\x14ORDER_STATE_CANCELED\x10\x05\x12 \n" +
	"\x1cORDER_STATE_PARTIAL_CANCELED\x10\x06\x12\x16\n" +
	"\x12ORDER_STATE_FAILED\x10\a\x12\x15\n" +
	"\x11ORDER_STATE_ERROR\x10\bB\x19Z\x17./exchange/internal/dtob\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_order_proto_goTypes = []any{
	(Side)(0),                 // 0: dto.Side
	(OrderType)(0),            // 1: dto.OrderType
	(SelfTradeWMType)(0),      // 2: dto.SelfTradeWMType
	(OrderState)(0),           // 3: dto.OrderState
	(*Order)(nil),             // 4: dto.Order
	(*OrderBookSnapshot)(nil), // 5: dto.OrderBookSnapshot
	(*OrderResult)(nil),       // 6: dto.OrderResult
	(*PriceLevel)(nil),        // 7: dto.PriceLevel
}
var file_order_proto_depIdxs = []int32{
	0,  // 0: dto.Order.side:type_name -> dto.Side
	1,  // 1: dto.Order.type:type_name -> dto.OrderType
	3,  // 2: dto.Order.state:type_name -> dto.OrderState
	2,  // 3: dto.Order.stp:type_name -> dto.SelfTradeWMType
	4,  // 4: dto.Order.pre:type_name -> dto.Order
	4,  // 5: dto.Order.next:type_name -> dto.Order
	7,  // 6: dto.Order.Parent:type_name -> dto.PriceLevel
	4,  // 7: dto.OrderBookSnapshot.asks:type_name -> dto.Order
	4,  // 8: dto.OrderBookSnapshot.bids:type_name -> dto.Order
	4,  // 9: dto.PriceLevel.head:type_name -> dto.Order
	4,  // 10: dto.PriceLevel.tail:type_name -> dto.Order
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	file_order_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		EnumInfos:         file_order_proto_enumTypes,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
