// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/pb/order_event.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operate int32

const (
	Operate_OpUnKnown Operate = 0
	Operate_OpAdd     Operate = 1
	Operate_OpDel     Operate = 2
	Operate_OpMod     Operate = 3
)

// Enum value maps for Operate.
var (
	Operate_name = map[int32]string{
		0: "OpUnKnown",
		1: "OpAdd",
		2: "OpDel",
		3: "OpMod",
	}
	Operate_value = map[string]int32{
		"OpUnKnown": 0,
		"OpAdd":     1,
		"OpDel":     2,
		"OpMod":     3,
	}
)

func (x Operate) Enum() *Operate {
	p := new(Operate)
	*p = x
	return p
}

func (x Operate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operate) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_order_event_proto_enumTypes[0].Descriptor()
}

func (Operate) Type() protoreflect.EnumType {
	return &file_internal_pb_order_event_proto_enumTypes[0]
}

func (x Operate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operate.Descriptor instead.
func (Operate) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_order_event_proto_rawDescGZIP(), []int{0}
}

type Priority int32

const (
	Priority_UnKnown Priority = 0
	Priority_High    Priority = 1
	Priority_Medium  Priority = 2
	Priority_Low     Priority = 3
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "UnKnown",
		1: "High",
		2: "Medium",
		3: "Low",
	}
	Priority_value = map[string]int32{
		"UnKnown": 0,
		"High":    1,
		"Medium":  2,
		"Low":     3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pb_order_event_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_internal_pb_order_event_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_internal_pb_order_event_proto_rawDescGZIP(), []int{1}
}

type OrderEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            Operate                `protobuf:"varint,1,opt,name=op,proto3,enum=dto.Operate" json:"op,omitempty"`
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	OrderId       int64                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amt           string                 `protobuf:"bytes,5,opt,name=amt,proto3" json:"amt,omitempty"`
	OrderState    OrderState             `protobuf:"varint,6,opt,name=order_state,json=orderState,proto3,enum=dto.OrderState" json:"order_state,omitempty"`
	Side          Side                   `protobuf:"varint,7,opt,name=side,proto3,enum=dto.Side" json:"side,omitempty"`
	Priority      Priority               `protobuf:"varint,8,opt,name=priority,proto3,enum=dto.Priority" json:"priority,omitempty"` // 冰山订单会使用到，在特定情况下，会影响订单在队列里的信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderEvent) Reset() {
	*x = OrderEvent{}
	mi := &file_internal_pb_order_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEvent) ProtoMessage() {}

func (x *OrderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_order_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEvent.ProtoReflect.Descriptor instead.
func (*OrderEvent) Descriptor() ([]byte, []int) {
	return file_internal_pb_order_event_proto_rawDescGZIP(), []int{0}
}

func (x *OrderEvent) GetOp() Operate {
	if x != nil {
		return x.Op
	}
	return Operate_OpUnKnown
}

func (x *OrderEvent) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *OrderEvent) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderEvent) GetAmt() string {
	if x != nil {
		return x.Amt
	}
	return ""
}

func (x *OrderEvent) GetOrderState() OrderState {
	if x != nil {
		return x.OrderState
	}
	return OrderState_ORDER_STATE_UNKNOWN
}

func (x *OrderEvent) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNKNOWN
}

func (x *OrderEvent) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_UnKnown
}

var File_internal_pb_order_event_proto protoreflect.FileDescriptor

const file_internal_pb_order_event_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/pb/order_event.proto\x12\x03dto\x1a\x17internal/pb/order.proto\"\x82\x02\n" +
	"\n" +
	"OrderEvent\x12\x1c\n" +
	"\x02op\x18\x01 \x01(\x0e2\f.dto.OperateR\x02op\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x10\n" +
	"\x03amt\x18\x05 \x01(\tR\x03amt\x120\n" +
	"\vorder_state\x18\x06 \x01(\x0e2\x0f.dto.OrderStateR\n" +
	"orderState\x12\x1d\n" +
	"\x04side\x18\a \x01(\x0e2\t.dto.SideR\x04side\x12)\n" +
	"\bpriority\x18\b \x01(\x0e2\r.dto.PriorityR\bpriority*9\n" +
	"\aOperate\x12\r\n" +
	"\tOpUnKnown\x10\x00\x12\t\n" +
	"\x05OpAdd\x10\x01\x12\t\n" +
	"\x05OpDel\x10\x02\x12\t\n" +
	"\x05OpMod\x10\x03*6\n" +
	"\bPriority\x12\v\n" +
	"\aUnKnown\x10\x00\x12\b\n" +
	"\x04High\x10\x01\x12\n" +
	"\n" +
	"\x06Medium\x10\x02\x12\a\n" +
	"\x03Low\x10\x03B\x12Z\x10internal/dto;dtob\x06proto3"

var (
	file_internal_pb_order_event_proto_rawDescOnce sync.Once
	file_internal_pb_order_event_proto_rawDescData []byte
)

func file_internal_pb_order_event_proto_rawDescGZIP() []byte {
	file_internal_pb_order_event_proto_rawDescOnce.Do(func() {
		file_internal_pb_order_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_order_event_proto_rawDesc), len(file_internal_pb_order_event_proto_rawDesc)))
	})
	return file_internal_pb_order_event_proto_rawDescData
}

var file_internal_pb_order_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_pb_order_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_pb_order_event_proto_goTypes = []any{
	(Operate)(0),       // 0: dto.Operate
	(Priority)(0),      // 1: dto.Priority
	(*OrderEvent)(nil), // 2: dto.OrderEvent
	(OrderState)(0),    // 3: dto.OrderState
	(Side)(0),          // 4: dto.Side
}
var file_internal_pb_order_event_proto_depIdxs = []int32{
	0, // 0: dto.OrderEvent.op:type_name -> dto.Operate
	3, // 1: dto.OrderEvent.order_state:type_name -> dto.OrderState
	4, // 2: dto.OrderEvent.side:type_name -> dto.Side
	1, // 3: dto.OrderEvent.priority:type_name -> dto.Priority
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_pb_order_event_proto_init() }
func file_internal_pb_order_event_proto_init() {
	if File_internal_pb_order_event_proto != nil {
		return
	}
	file_internal_pb_order_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_order_event_proto_rawDesc), len(file_internal_pb_order_event_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_order_event_proto_goTypes,
		DependencyIndexes: file_internal_pb_order_event_proto_depIdxs,
		EnumInfos:         file_internal_pb_order_event_proto_enumTypes,
		MessageInfos:      file_internal_pb_order_event_proto_msgTypes,
	}.Build()
	File_internal_pb_order_event_proto = out.File
	file_internal_pb_order_event_proto_goTypes = nil
	file_internal_pb_order_event_proto_depIdxs = nil
}
